PROGRAM SarahRevere(INPUT, OUTPUT);
USES
  DOS;
BEGIN {Response}
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('REQUEST_METHOD: ', GETENV('REQUEST_METHOD'));
  WRITELN('QUERY_STRING: ', GETENV('QUERY_STRING'));
  WRITELN('CONTENT_LENGTH: ', GETENV('CONTENT_LENGTH'));
  WRITELN('HTTP_USER_AGENT: ', GETENV('HTTP_USER_AGENT'));
  WRITELN('HTTP_HOST: ', GETENV('HTTP_HOST'))
END. {Response}
